### ISSUE TITLE
Make repeats less likely

### ISSUE THREAD

**Issue by andrewstellman** [xori/gamblers-dice#1]
I think it would be even better if rolling a 3 would make it less likely that the next roll would be a 3, and rolling two 3s would make it even less likely to roll a third, etc. This should still keep it uniformly random over time but would make it marginally funnier.

**Comment by xori** [comment]
It actually should already do that. But with diminishing returns.

| Roll| % of 1 | % of 2 | % of 3 | % of 4 | Actual Roll |
| --- | --- | --- | --- | --- | --- |
| 1 | 25% | 25% | 25% | 25% | 3 |
| 2 | 29% | 29% | 14% | 29% | 3 |
| 3 | 30% | 30% | 10% | 30% | 3 |
| 4 | 31% | 31% | 8% | 31% | 3 |
| 5 | 31% | 31% | 6% | 31% | 3 |
| 6 | 32% | 32% | 5% | 32% | - |
