### ISSUE TITLE
[Request] Python 3 Port

### ISSUE THREAD

**Issue by JCharante** [xori/gamblers-dice#11]
Just letting it be known that I'd be interested in a Python 3 port

**Comment by Torvaney** [comment]
Whipped this up this evening and it's compatible with Python 2.7 and up: https://github.com/Torvaney/gamblers-dice

Could be what you're looking for, @JCharante?

**Comment by JCharante** [comment]
@Torvaney perfect! We should get that added to the readme section for ports

**Comment by xori** [comment]
Merged in with bcea5ccb74
