### ISSUE TITLE
Ensure your entropy

### ISSUE THREAD

**Issue by Nectarineimp** [xori/gamblers-dice#2]
Me? I am a data scientist for a company that makes slot machines. I know a thing or two about probabilities. I freaking love this. I can see a game being made using this. Not a gambling game, because it would never get past even the most easily bought off federal compliance officer in the land. However, regular games could benefit from this mechanism. A system where you luck is always turning on you...

Also, to ensure your odds, you need very high entropy. Sure, go ahead and use your mersene twister. Its the defacto default. However, if you ever go live with something that depends upon this for millions of game sessions (hey, think BIG), then use any one of several schemes to insure the entropy is excellent. Like sigma 15 excellent.

You can mark this closed. Its just a suggestion! Good work!

**Comment by SEAPUNK** [comment]
[`RandomSource.getRandomValues`](https://developer.mozilla.org/en-US/docs/Web/API/RandomSource/getRandomValues)?
[random.org API](https://api.random.org/json-rpc/1/)?

**Comment by Nectarineimp** [comment]
Those work. One thing I've done for offline entropy is to create high entropy sets and randomize them. It requires disk space or memory, but can save a lot of processing time in real time. The lower the entropy, the longer it takes for the system to give theoretical results.

I wonder if in an interactive game with several people, if it matters if everyone used the same dice? Would individual results differ from using standard dice, even if the group result was clearly modified? I shouldn't ask such questions. They usually end up being solved with a wasted weekend of CUDA programming...
