### ISSUE TITLE
true uniformity

### ISSUE THREAD

**Issue by danschumann** [xori/gamblers-dice#4]
You could populate each side like a deck of cards...

1000 1's
1000 2's
1000 3's

Then, when people rolled, eventually they would reach true uniformity (in this example after 3000 rolls)

Maybe have this accessible by a different "engine" property, (or "algorithm", or "sampleType" or whatever you want to call it)

You could also pick the initial sample size (aka, reaches uniformity every 1000, or every 10, or every 100).

This would allow people to 'count cards' in a sense ( count die ).
Just an idea!

And, people would think "I haven't rolled 3 in a while", they'd be right to think that because there are a lot of 3's left in the "deck".

**Comment by danschumann** [comment]
And after they hit the 3000 mark, it would just reset to a new "deck"

**Comment by jdarcy** [comment]
Problem is, that would make the last card in a deck 100% predictable.  What you should do instead is replenish the deck *continuously* or nearly so, to maintain almost the same distributional properties without being quite so predictable.

**Comment by xori** [comment]
>I made a chatbot that rolled dice, and it was constantly criticized for being "broken" because four 3's would come up in a row.

This is the true purpose for creating this library, and the problem with the card solution is that until you empty a card pile the numbers generated could produce strings of numbers that repeat. Something that this library ensures is _very_ unlikely.
