### ISSUE TITLE
Either I dont understand or this dosen't works

### ISSUE THREAD

**Issue by imerkle** [xori/gamblers-dice#8]
So i tried this and if i understand correctly this dont work . tried with 4 also.  help. 

https://www.webpackbin.com/bins/-KpU3Tf83tTgzq_Xxq1o

its always uniformly distributed .

**Comment by cassdeckard** [comment]
The README says in the first paragraph the results are still uniformly distributed.

**Comment by xori** [comment]
It's uniformly distributed for _large_ sample sets. But for small ones, it's not. A downside is that it is prone to cycling for dice sizes that are small (like d4s) to the point where you can (with >25% accuracy) predict the next number.

Take a look at https://cletusw.github.io/gamblers-dice and choose a small dice size and see if you can predict what it will be based on the previous rolls. Your success rate should be higher than if you did it with a regular die, which is the point.
